#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
$autoloadPath = __DIR__.'/vendor/autoload.php';

if (! file_exists($autoloadPath)) {
    fwrite(
        STDERR,
        "Composer dependencies are missing. Please run 'composer install' before executing Artisan commands.\n"
    );

    exit(1);
}

require $autoloadPath;

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
